#!/usr/bin/env node 
'use strict';
var proxy = require('./proxy.js');
var cli = require('meow')({
  pkg: "./package.json",
  help: [
      'Usage',
      '  $ tunnel-proxy [options]',
      '\n  options:',
      '\t -p\t     change proxy port number (default: 3000)',
      '\t -s\t     change max sockets (default: 300)',
      '\t -h\t     change target url header name (default: target)',
      '\t -q\t     stay quiet, don\'t console log (default: false)',
      '\t -v\t     verbose mode logs har output (default: false)',
      '\t -k\t     apianalytics.com api key (optional)',
      '\t -t\t     apianalytics.com transport layer (default: socket.io)',
      '\t --help   output usage and help information',
      '\t --version   output the current version of tunnel-proxy',
      '\n  examples:',
      '\t tunnel-proxy -h "baseurl"',
      '\t tunnel-proxy -q -p 8080',
      '\t tunnel-proxy -t "zeromq" -k "54adbfffeba3f94b5182carr"',
  ].join('\n')
});

var opts = {
  port: cli.flags.p,
  sockets: cli.flags.s,
  quiet: cli.flags.q,
  header: cli.flags.h,
  verbose: cli.flags.v,
  key: cli.flags.k,
  transport: cli.flags.t
};

proxy(opts);
